// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ID_CMD_FRAC 2 
#define ID_CMD_FRAC_LabelTitle_RESID 60001
#define ID_CMD_FRAC_LabelDescription_RESID 60002
#define ID_CMD_FRAC_TooltipDescription_RESID 60003
#define ID_CMD_FRAC_LargeImages_RESID 60004
#define ID_CMD_DEGR 3 
#define ID_CMD_DEGR_LabelTitle_RESID 60005
#define ID_CMD_DEGR_LabelDescription_RESID 60006
#define ID_CMD_DEGR_TooltipDescription_RESID 60007
#define ID_CMD_DEGR_LargeImages_RESID 60008
#define ID_CMD_SUBSCRIPT 4 
#define ID_CMD_SUBSCRIPT_LabelTitle_RESID 60009
#define ID_CMD_SUBSCRIPT_LabelDescription_RESID 60010
#define ID_CMD_SUBSCRIPT_TooltipDescription_RESID 60011
#define ID_CMD_SUBSCRIPT_LargeImages_RESID 60012
#define ID_CMD_RADICAL 5 
#define ID_CMD_RADICAL_LabelTitle_RESID 60013
#define ID_CMD_RADICAL_LabelDescription_RESID 60014
#define ID_CMD_RADICAL_TooltipDescription_RESID 60015
#define ID_CMD_RADICAL_LargeImages_RESID 60016
#define ID_CMD_Parantheses 6 
#define ID_CMD_Parantheses_LabelTitle_RESID 60017
#define ID_CMD_Parantheses_LabelDescription_RESID 60018
#define ID_CMD_Parantheses_TooltipDescription_RESID 60019
#define ID_CMD_Parantheses_LargeImages_RESID 60020
#define ID_CMD_SquareBrackets 7 
#define ID_CMD_SquareBrackets_LabelTitle_RESID 60021
#define ID_CMD_SquareBrackets_LabelDescription_RESID 60022
#define ID_CMD_SquareBrackets_TooltipDescription_RESID 60023
#define ID_CMD_SquareBrackets_LargeImages_RESID 60024
#define ID_CMD_Braces 8 
#define ID_CMD_Braces_LabelTitle_RESID 60025
#define ID_CMD_Braces_LabelDescription_RESID 60026
#define ID_CMD_Braces_TooltipDescription_RESID 60027
#define ID_CMD_Braces_LargeImages_RESID 60028
#define ID_CMD_Sum 9 
#define ID_CMD_Sum_LabelTitle_RESID 60029
#define ID_CMD_Sum_LabelDescription_RESID 60030
#define ID_CMD_Sum_TooltipDescription_RESID 60031
#define ID_CMD_Sum_LargeImages_RESID 60032
#define ID_CMD_Product 10 
#define ID_CMD_Product_LabelTitle_RESID 60033
#define ID_CMD_Product_LabelDescription_RESID 60034
#define ID_CMD_Product_TooltipDescription_RESID 60035
#define ID_CMD_Product_LargeImages_RESID 60036
#define ID_CMD_System 11 
#define ID_CMD_System_LabelTitle_RESID 60037
#define ID_CMD_System_LabelDescription_RESID 60038
#define ID_CMD_System_TooltipDescription_RESID 60039
#define ID_CMD_System_LargeImages_RESID 60040
#define ID_CMD_EXIT 12 
#define ID_CMD_EXIT_LabelTitle_RESID 60041
#define ID_CMD_EXIT_LabelDescription_RESID 60042
#define ID_CMD_EXIT_TooltipDescription_RESID 60043
#define ID_CMD_EXIT_LargeImages_RESID 60044
#define ID_CMD_SAVE 13 
#define ID_CMD_SAVE_LabelTitle_RESID 60045
#define ID_CMD_SAVE_LabelDescription_RESID 60046
#define ID_CMD_SAVE_TooltipDescription_RESID 60047
#define ID_CMD_SAVE_LargeImages_RESID 60048
#define ID_CMD_TAB_MAIN 14 
#define ID_CMD_TAB_MAIN_LabelTitle_RESID 60049
#define ID_CMD_TAB_MORE 15 
#define ID_CMD_TAB_MORE_LabelTitle_RESID 60050
#define ID_CMD_GROUP_FILE 16 
#define ID_CMD_GROUP_FILE_LabelTitle_RESID 60051
#define ID_CMD_GROUP_BRACKET 17 
#define ID_CMD_GROUP_BRACKET_LabelTitle_RESID 60052
#define ID_CMD_GROUP_SUM_PRODUCT 18 
#define ID_CMD_GROUP_SUM_PRODUCT_LabelTitle_RESID 60053
#define ID_CMD_GROUP_SYSTEM 19 
#define ID_CMD_GROUP_SYSTEM_LabelTitle_RESID 60054
#define ID_CMD_GROUP_EXIT 20 
#define ID_CMD_GROUP_EXIT_LabelTitle_RESID 60055
#define ID_CMD_MORE 21 
#define ID_CMD_MORE_LabelTitle_RESID 60056
#define InternalCmd2_LabelTitle_RESID 60057
